name: first workflow

env:
  WORKFLOW_VAR: "my var"
on:
  workflow_dispatch:

jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo "Hello World"
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ github.actor }} #$GITHUB_ACTOR
      - name: time
        run: |
          echo "The time of the greeting was at ${{ steps.print-to-log.outputs.time }}"

  secondJob:
    needs: firstJob
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "this is a job var"
    steps:
      - name: secondJob script
        shell: bash
        run: echo "Hello World from second job"
      - name: environment variable
        env:
          STEP_VAR: "this is a steplvl  var"
        run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo "The following is a secret: ${{ secrets.SOME_SECRET }}"
